### ISSUE TITLE
[FEATURE-REQUEST] Reduce padding around content on mobile

### ISSUE THREAD

**Issue by axelclark** [aesmail/kaffy#108]
**Describe the problem you're proposing to solve**
On mobile, there is a lot of padding around the main content.

**Describe the solution you'd like**
Suggest reducing the padding so the main content fills more of the screen.

**Describe alternatives you've considered**
NA

**Additional context**
![6F850581-E9D5-4450-B99E-59639618E675](https://user-images.githubusercontent.com/16856928/84971486-e0e28980-b0ea-11ea-8295-f076da16ff9b.png)

**Comment by aesmail** [comment]
Yes I totally agree.
I think the best solution here is to use extra css classes on the container to change the behavior for different screen sizes.
This has been bugging me for some time now.
I have some time to spend on Kaffy today so a few things will get done hopefully.

**Comment by axelclark** [comment]
I think moving the `padding 2.75rem 2.25rem;` into a media query would add the padding on the same break point as the sidebar expanding.  However, I can't get the css to update in my project using the repo I cloned, so I'm not 100% sure it works.

```scss
/* priv/static/assets/scss/_vertical-wrapper.scss */
.content-wrapper {
  background: $content-bg;
  padding: 0rem 0rem;
  width: 100%;
  @include flex-grow(1);
  @media (max-width: 991px) {
    padding: 2.75rem 2.25rem;
  }
}
```
